name: CI/CD for ANN Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/banknote-ann-api
  K8S_DEPLOYMENT: k8s-deployment.yaml
  K8S_NAMESPACE: default

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_IMAGE:latest .
          docker push $DOCKER_IMAGE:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Setup Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/banknote-ann-api banknote-ann-api=$DOCKER_IMAGE:latest -n $K8S_NAMESPACE
          kubectl rollout status deployment/banknote-ann-api -n $K8S_NAMESPACE
